### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by kcirekcom** [benpetty/BenPetty.me#27]
1. I really enjoy the feel of the website. It's also very easy to navigate and the nav bar hover effects are awesome.

2. Every piece of code in your files is well commented for the most part. Helps with navigating through the code and seeing how everything is functioning. That being said, I was a little lost in your projectView.js file and didn't understand why the adjustIframes() method is called five times in your handleMainNav function. I commented out all but one and it seemed to work fine, but I'm also not as familiar with your code base so perhaps I'm missing what it may be doing.

3. I noticed that you have an app.js file with a get-to-know-you game in your code base. Do you plan on re-implementing that in your portfolio site?

4. Great job with the media queries and responsiveness! Everything snaps into place seamlessly. I like how your background image is also responsive. It creates consistency across your website.

**Comment by benpetty** [comment]
Thanks, Erick!
